version: '3'
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${PWD}/data/mysqldir:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=dataeng
      - MYSQL_PASSWORD=dataengineering_user
      - MYSQL_ROOT_PASSWORD=dataengineering
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - oasiscorp
    hostname: mysql
  
  zeppelin:
    image: 'spark-zep'
    container_name: zeppelin
    volumes:
      - ${PWD}/notebook:/notebook
      - ${PWD}/logs:/logs
      - ${PWD}/data:/learn
      - ${PWD}/spark/conf:/spark/conf
      - ${PWD}/spark/jars:/spark/user_jars
      - ${PWD}/spark/sql/:/spark/sql/
    environment:
      - SPARK_SUBMIT_OPTIONS=--packages=org.mariadb.jdbc:mariadb-java-client:2.7.2 --jars=/spark/user_jars/mysql-connector-java-8.0.23.jar
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SPARK_MAXRESULT=10000
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=204800
      - ZEPPELIN_NOTEBOOK_COLLABORATIVE_MODE_ENABLE=false
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 8080:8080
      - 4040:4040
      - 4041:4041
    networks:
      - oasiscorp
    hostname: "zeppelin"
    depends_on:
      - mysql

# Network Bridge Connection
networks:
  oasiscorp:
    name: oasiscorp
    driver: bridge